package dev.sanda.apifi.annotations;

import dev.sanda.datafi.annotations.finders.FindAllBy;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * When placed on a field of a JPA Entity annotated class
 * this annotation tells apifi to autogenerate an endpoint
 * for finding all instances of said JPA Entity class
 * with a field value contained within a list of provided values.
 *
 * For example:
 * <pre>{@code
 * @Data
 * @Entity
 * public class User {
 *   @Id
 *   @GeneratedValue
 *   private Long id;
 *   @ApiFindAllBy
 *   private String name;
 *   //...
 * }
 * }</pre>
 * Will translate into the following GraphQL query resolver:
 * <pre>{@Code
 *   @GraphQLQuery
 *   public List<User> findUsersByNames(List<String> names) {
 *     return apiLogic.apiFindAllBy("name", names); // internal logic
 *   }
 * }</pre>
 */
@Target({ ElementType.FIELD, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@FindAllBy
public @interface ApiFindAllBy {
  String secured() default "";

  /**
   * spring security annotations denoting
   * authorization policies  to accessing the autogenerated
   * query resolver method
   */

  String[] rolesAllowed() default "";

  String preAuthorize() default "";

  String postAuthorize() default "";

  String preFilter() default "";

  String preFilterTarget() default "";

  String postFilter() default "";
}
