package dev.sanda.apifi.annotations;

import dev.sanda.datafi.annotations.finders.FindByUnique;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * When placed on a field of a JPA Entity annotated class
 * this annotation tells apifi to autogenerate an endpoint
 * for finding a single instance of said JPA Entity class
 * with a field value matching a provided argument value.
 *
 * For example:
 * <pre>{@code
 * @Data
 * @Entity
 * public class User {
 *   @Id
 *   @GeneratedValue
 *   private Long id;
 *   @ApiFindByUnique
 *   @Column(unique = true) // this is required
 *   private String username;
 *   //...
 * }
 * }</pre>
 * Will translate into the following GraphQL query resolver:
 * <pre>{@Code
 *   @GraphQLQuery
 *   public User findUserByUniqueUsername(String username) {
 *     return apiLogic.apiFindByUnique("username", username);
 *   }
 * }</pre>
 */
@FindByUnique
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.FIELD, ElementType.METHOD })
public @interface ApiFindByUnique {
  /**
   * spring security annotations denoting
   * authorization policies  to accessing the autogenerated
   * query resolver method
   */

  String secured() default "";

  String[] rolesAllowed() default "";

  String preAuthorize() default "";

  String postAuthorize() default "";

  String preFilter() default "";

  String preFilterTarget() default "";

  String postFilter() default "";
}
