package org.sindaryn.apifi.annotations;


import org.sindaryn.apifi.service.ApiMetaOperations;

import java.lang.annotation.*;

/**
 * Marks an entity for inclusion within the autogenerated api
 */

@Inherited
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface GraphQLApiEntity {
    /*
    i.e. - expose the generated mutations and queries on the api schema, as opposed to
           not having them exposed, and only being able to access and mutate the given entity
           via an owning entity with a foreign key. This is similar to the concept of "strong"
           vs "weak" entities in relational database design.
    */
    boolean exposeDirectly() default true;
    //expose only the queries, not the mutations.
    boolean readOnly() default false;
    //custom logic to be executed before and  / or after mutations
    Class<? extends ApiMetaOperations> apiMetaOperations() default ApiMetaOperations.class;
}
